### PR TITLE
Random sleeping

### PR DESCRIPTION
**Pull request by ktsour**
Add random sleep times, so that we avoid CPU drain.

### CODE REVIEW

**Comment by wumpz** [comment]
What purpose does this change have or better what symptoms do you want to cure with it? Diff should run in a background thread. There you could prioritize it. A much better way to control the thread IMHO would be some kind of process listener.

**Comment by ktsour** [comment]
I did try to prioritize the thread, but the linux system did not show much response to the request. We are diffing two files 4GB each and the CPU goes up to 90%, making the whole server unavailable. I cannot find any references to what you referred to as "process listener". So, my only solution was to put some make the thread sleep while looping and it solved the CPU problem. If you think there are other ways to achieve the same, please post some reference link so I can look further. Thank you.

**Comment by wumpz** [comment]
With process listener I mean a simple listener that gets called every processed line or so, so nothing special. That would be an improvement of java diff utils. Then you could put in your CPU nap times in those listener callbacks. But the diff tools itself should never be bothered with something like sleep directly.

I opened already an issue for this.

Cheers Tobias

**Comment by ktsour** [comment]
OK this sounds fine, yet since it is a CPU intensive task, I don't see why not provide the functionality out-of-the-box. It is optional anyway, you can use the default constructor which uses no sleeps, or use the constructor with the new functionality. So, whoever wants uses it, or one can use the listeners to plugin other custom logic. Anyway, it's just a suggestion.

**Comment by wumpz** [comment]
The listener are some kind of extension points for this library, so it is a general purpose improvement.

The "sleep" functionality is some kine of cross cutting concern, dealing with a special environment. To keep it clean and simple this should be done using the extension above. (some kine of single responsibility principle). In a sense with the same argument I discarded some of the old html generating code and replaced it with a supplier interface.

So nevermind. I will look into this listener concept.

**Comment by wumpz** [comment]
I introduced a listener concept. Could you take a look, if you could implement a solution based on this?

cheers Tobias

**Pull request closed without merging**
